databases:
  - name: carboncopydb
    plan: free
    databaseName: carboncopy
    user: carboncopy

services:
  - type: web
    plan: free
    name: carboncopy
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn carboncopy.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: carboncopydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
