# Generated by Django 5.2.1 on 2025-06-30 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('db_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='AggregateMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('aggregation_method', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('MIN', 'Minimum'), ('MAX', 'Maximum'), ('COUNT', 'Count')], default='SUM', max_length=10)),
                ('categories', models.ManyToManyField(blank=True, related_name='aggregate_metrics', to='projects.category')),
                ('project_metrics', models.ManyToManyField(related_name='aggregate_metrics', to='metrics.projectmetric')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetricMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('client', 'Project supplied'), ('dune', 'Dune API'), ('graphql', 'Subghraph index'), ('near', 'Near blockchain'), ('regen', 'Regen blockchain')], default='Project supplied', max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('query', models.CharField(max_length=1000)),
                ('json_key', models.CharField(max_length=1000)),
                ('conversion_ratio', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta', to='projects.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='projectmetric',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.projectmetricmeta'),
        ),
        migrations.CreateModel(
            name='ProjectMetricDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='metrics.projectmetricmeta')),
            ],
            options={
                'unique_together': {('timestamp',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectmetric',
            unique_together={('timestamp',)},
        ),
    ]
