# Generated by Django 5.2.1 on 2025-05-16 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmetric',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterUniqueTogether(
            name='projectmetric',
            unique_together={('timestamp',)},
        ),
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProjectMetricMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('conversion_ratio', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta', to='metrics.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='metrics.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='projectmetric',
            name='meta',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metrics.projectmetricmeta'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='id',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectmetric',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectMetricDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='metrics.projectmetricmeta')),
            ],
            options={
                'unique_together': {('timestamp',)},
            },
        ),
    ]
