# Generated by Django 5.2.1 on 2025-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(choices=[('client', 'Project supplied'), ('dune', 'Dune API'), ('graphql', 'Subghraph index'), ('near', 'Near blockchain'), ('regen', 'Regen blockchain')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
